#include "PMUICX.h"
#include "Debug.h"

// https://perfmon-events.intel.com/icelake_server.html

#define NCOUNTERS                     8

#define INST_RETIRED                  0xc0
#define CPU_CLK_UNHALTED              0x3c
#define UOPS_ISSUED_ANY               0x0e|(0x01<<8)
#define UOPS_RETIRED_SLOTS            0xc2|(0x02<<8)
#define INT_MISC_ALL_RECOVERY_CYCLES  0x0d|(0x03<<8)|(0x01<<24)
#define IDQ_UOPS_NOT_DELIVERED_CORE   0x9c|(0x01<<8)
#define TOPDOWN_SLOTS                 0xa4|(0x01<<8)
#define TOPDOWN_BACKEND_BOUND_SLOTS   0xa4|(0x02<<8)
#define BR_INST_RETIRED_ALL_BRANCHES  0xc4|(0x00<<8)
#define BR_MISP_RETIRED_ALL_BRANCHES  0xc5|(0x00<<8)
#define MEM_INST_RETIRED_ALL_LOADS    0xd0|(0x81<<8)
#define MEM_INST_RETIRED_ALL_STORES   0xd0|(0x82<<8)
#define MEM_LOAD_RETIRED_L1_HIT       0xd1|(0x01<<8)
#define MEM_LOAD_RETIRED_L1_MISS      0xd1|(0x08<<8)
#define MEM_LOAD_RETIRED_L2_HIT       0xd1|(0x02<<8)
#define MEM_LOAD_RETIRED_L2_MISS      0xd1|(0x10<<8)
#define MEM_LOAD_RETIRED_L3_HIT       0xd1|(0x04<<8)
#define MEM_LOAD_RETIRED_L3_MISS      0xd1|(0x20<<8)

namespace trendline {

PMUICX::PMUICX() {
  ncounters_ = NCOUNTERS;
  ngroups_ = 4;
  events_ = new int[ngroups_ * NCOUNTERS] {
    CPU_CLK_UNHALTED, INST_RETIRED, TOPDOWN_SLOTS, UOPS_ISSUED_ANY, UOPS_RETIRED_SLOTS, INT_MISC_ALL_RECOVERY_CYCLES, IDQ_UOPS_NOT_DELIVERED_CORE, TOPDOWN_BACKEND_BOUND_SLOTS,
    BR_INST_RETIRED_ALL_BRANCHES, BR_MISP_RETIRED_ALL_BRANCHES, -1, -1, -1, -1, -1, -1,
    MEM_INST_RETIRED_ALL_LOADS, MEM_INST_RETIRED_ALL_STORES, MEM_LOAD_RETIRED_L1_HIT, MEM_LOAD_RETIRED_L1_MISS, -1, -1, -1, -1,
    MEM_LOAD_RETIRED_L2_HIT, MEM_LOAD_RETIRED_L2_MISS, MEM_LOAD_RETIRED_L3_HIT, MEM_LOAD_RETIRED_L3_MISS, -1, -1, -1, -1
  };
  InitS2E();
  InitE2S();
}

PMUICX::~PMUICX() {

}

int PMUICX::InitS2E() {
  S2E(INST_RETIRED);
  S2E(CPU_CLK_UNHALTED);
  S2E(UOPS_ISSUED_ANY);
  S2E(UOPS_RETIRED_SLOTS);
  S2E(INT_MISC_ALL_RECOVERY_CYCLES);
  S2E(IDQ_UOPS_NOT_DELIVERED_CORE);
  S2E(TOPDOWN_SLOTS);
  S2E(TOPDOWN_BACKEND_BOUND_SLOTS);
  S2E(BR_INST_RETIRED_ALL_BRANCHES);
  S2E(BR_MISP_RETIRED_ALL_BRANCHES);
  S2E(MEM_INST_RETIRED_ALL_LOADS);
  S2E(MEM_INST_RETIRED_ALL_STORES);
  S2E(MEM_LOAD_RETIRED_L1_HIT);
  S2E(MEM_LOAD_RETIRED_L1_MISS);
  S2E(MEM_LOAD_RETIRED_L2_HIT);
  S2E(MEM_LOAD_RETIRED_L2_MISS);
  S2E(MEM_LOAD_RETIRED_L3_HIT);
  S2E(MEM_LOAD_RETIRED_L3_MISS);
  return TRENDLINE_OK;
}

int* PMUICX::Events(int i) {
  return ((int(*)[NCOUNTERS]) (events_))[i];
}

} /* namespace trendline */

